const Avalon = require('./avalon.js')

const g = new Avalon.Game({
    knights: 6,
    minions: 4,
    specials: ['Merlin', 'Morgana', 'Percival']
})

console.log(g.history)
g.join('Tobin')
g.join('Noah')
g.join('Ben')
g.join('Bryan')
g.join('Oliver')
g.join('Sean')
g.join('Natalie')
g.join('Sam')
g.join('Alistair')
g.join('Delaney')
console.log(g.history)
console.log(g.history)

console.log('It is ' + g.turn + '\'s turn.')
g.propose(g.turn, ['Noah', 'Ben', 'Tobin'])
console.log(g.state)
g.player('Tobin').vote('accept')
console.log(g.state)
g.player('Noah').vote('reject')
console.log(g.state)
g.player('Ben').vote('accept')
console.log(g.state)
g.player('Bryan').vote('reject')
console.log(g.state)
g.player('Oliver').vote('accept')
console.log(g.state)
g.player('Sean').vote('accept')
console.log(g.state)
g.player('Natalie').vote('reject')
console.log(g.state)
g.player('Sam').vote('accept')
console.log(g.state)
g.player('Alistair').vote('reject')
console.log(g.state)
g.player('Delaney').vote('accept')
console.log(g.state)
console.log('The mission was ' + (g.currentMission.accepted ? 'accepted' : 'rejected') + '.')

g.player('Oliver').commit('fail')
g.player('Ben').commit('fail')
g.player('Noah').commit('pass')
g.player('Tobin').commit('pass')
console.log(g.state)
console.log('The mission ' + (g.currentMission.passed ? 'passed' : 'failed') + '.')
console.log(g.currentPlayer.name)
